### ISSUE TITLE
Create a Jekyll theme that implements the Italia Design Guidelines

### ISSUE THREAD

**Issue by ruphy** [italia/design-jekyll-theme#1]
Create a theme for Jekyll based on the [User Interface design guidelines](
https://design-italia.readthedocs.io/it/stable/doc/user-interface.html).

Do include [the design web toolkit](https://github.com/italia/design-web-toolkit) as a dependency, and make sure you write your code in a way which is generic enough so that, later on, it be replaced by another toolkit (e.g. bootstrap) without too much effort.

Some example websites with the correct style
https://developers.italia.it
https://designers.italia.it

**GSoC mentor**: Somebody from in the #design team. If you are unsure who to ask you can check out https://slack.developers.italia.it

**Comment by ruphy** [comment]
@vito80ba are you working on this?

**Comment by vito80ba** [comment]
yes

**Comment by ruphy** [comment]
thanks, not closing then!

**Comment by ggentili** [comment]
https://github.com/ggentili/Italia-Design-Jekyll-Theme/
