### ISSUE TITLE
Attribute class redefined

### ISSUE THREAD

**Issue by libremente** [italia/design-jekyll-theme#5]
In the lang-switcher there is an `Attribute class redefined` error. 
This means that there is a double `class` definition. 
See this line for reference:
https://github.com/italia/design-jekyll-theme/blob/1f36e25cfce17fb2d9dd13aa6005af17f10e5fd3/_includes/header/header-lang-switch.html#L18

I'd suggest writing something like this:
```html
 <li><a  href="{{ site.baseurl }}{{ linked_page.url }}" title="{{ site.data.t.italian-version[page.lang] }}" class="list-item {% if linked_page.lang == page.lang%}active{% endif %}"><span>{{ linked_page.lang | upcase }}</span></a></li>
```
which appends the `active` parameter to the already existing class.

**Comment by francescozaia** [comment]
Fixed by #6
